language: lua

env:
  - LUA=""
  - LUA="luajit"

install:
  - sudo apt-get install luajit
  - sudo apt-get install luarocks
  - sudo luarocks install luafilesystem
  - sudo luarocks install busted
  - sudo luarocks install luacheck

script:
  - busted -m=./?/init.lua
  - luacheck .
