name: Validate lua code

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y luajit lua-check lua-busted
    - name: Run luacheck
      run: luacheck .
    - name: Run unit tests
      run: busted -m=./?/init.lua