name: Validate lua code

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v4
    - run: sudo apt-get update && sudo apt-get install -y luajit lua-check
    - run: luacheck .